version: "4.29.0"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./nginx.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
  php:
    image: php:8.3.6-fpm
    volumes:
      - ./code:/code